
const ALL_PRODUCT = [
    {
      name: "HAVIT HV-G92 Gamepad",
      price1: "$120",
      price2: "$160",
      image: "/src/images/products/1.png",
      rating: {
        image1: "/src/images/icon/star.png",
        image2: "/src/images/icon/star.png",
        image3: "/src/images/icon/star.png",
        image4: "/src/images/icon/star.png",
        image5: "/src/images/icon/star.png",
      },
      offer: "",
      review: "88",
    },
    {
      name: "AK-900 Wired Keyboard",
      price1: "$960",
      price2: "$1160",
      image: "/src/images/products/2.png",
      rating: {
        image1: "/src/images/icon/star.png",
        image2: "/src/images/icon/star.png",
        image3: "/src/images/icon/star.png",
        image4: "/src/images/icon/star.png",
        image5: "/src/images/icon/noStar.png",
      },
      offer: "",
      review: "75",
    },
    {
      name: "IPS LCD Gaming Monitor",
      price1: "$370",
      price2: "$400",
      image: "/src/images/products/3.png",
      rating: {
        image1: "/src/images/icon/star.png",
        image2: "/src/images/icon/star.png",
        image3: "/src/images/icon/star.png",
        image4: "/src/images/icon/star.png",
        image5: "/src/images/icon/star.png",
      },
      offer: "",
      review: "99",
    },
    {
      name: "S-Series Comfort Chair ",
      price1: "$375",
      price2: "$400",
      image: "/src/images/products/4.png",
      rating: {
        image1: "/src/images/icon/star.png",
        image2: "/src/images/icon/star.png",
        image3: "/src/images/icon/star.png",
        image4: "/src/images/icon/star.png",
        image5: "/src/images/icon/star-half-filled.png",
      },
      offer: "",
      review: "99",
    },
    {
      name: "The north coat",
      price1: "$260",
      price2: "$360",
      image: "/src/images/products/5.png",
      rating: {
        image1: "/src/images/icon/star.png",
        image2: "/src/images/icon/star.png",
        image3: "/src/images/icon/star.png",
        image4: "/src/images/icon/star.png",
        image5: "/src/images/icon/star.png",
      },
      offer: "",
      review: "70",
    },
    {
      name: "Gucci duffle bag",
      price1: "$960",
      price2: "",
      image: "/src/images/products/6.png",
      rating: {
        image1: "/src/images/icon/star.png",
        image2: "/src/images/icon/star.png",
        image3: "/src/images/icon/star.png",
        image4: "/src/images/icon/star.png",
        image5: "/src/images/icon/star-half-filled.png",
      },
      offer: "",
      review: "65",
    },
    {
      name: "RGB liquid CPU Cooler",
      price1: "$160",
      price2: "",
      image: "/src/images/products/7.png",
      rating: {
        image1: "/src/images/icon/star.png",
        image2: "/src/images/icon/star.png",
        image3: "/src/images/icon/star.png",
        image4: "/src/images/icon/star.png",
        image5: "/src/images/icon/star-half-filled.png",
      },
      offer: "",
      review: "65",
    },
    {
      name: "Small BookSelf",
      price1: "$360",
      price2: "",
      image: "/src/images/products/9.png",
      rating: {
        image1: "/src/images/icon/star.png",
        image2: "/src/images/icon/star.png",
        image3: "/src/images/icon/star.png",
        image4: "/src/images/icon/star.png",
        image5: "/src/images/icon/star.png",
      },
      offer: "",
      review: "65",
    },
    {
      name: "Breed Dry Dog Food",
      price1: "$100",
      price2: "",
      image: "/src/images/products/10.png",
      rating: {
        image1: "/src/images/icon/star.png",
        image2: "/src/images/icon/star.png",
        image3: "/src/images/icon/star.png",
        image4: "/src/images/icon/noStar.png",
        image5: "/src/images/icon/noStar.png",
      },
      offer: "",
      review: "35",
    },
    {
      name: "CANON EOS DSLR Camera",
      price1: "$360",
      price2: "",
      image: "/src/images/products/11.png",
      rating: {
        image1: "/src/images/icon/star.png",
        image2: "/src/images/icon/star.png",
        image3: "/src/images/icon/star.png",
        image4: "/src/images/icon/star.png",
        image5: "/src/images/icon/noStar.png",
      },
      offer: "",
      review: "95",
    },
    {
      name: "ASUS FHD Gaming Laptop",
      price1: "$700",
      price2: "",
      image: "/src/images/products/12.png",
      rating: {
        image1: "/src/images/icon/star.png",
        image2: "/src/images/icon/star.png",
        image3: "/src/images/icon/star.png",
        image4: "/src/images/icon/star.png",
        image5: "/src/images/icon/star.png",
      },
      offer: "",
      review: "325",
    },
    {
      name: "Curology Product Set ",
      price1: "$500",
      price2: "",
      image: "/src/images/products/13.png",
      rating: {
        image1: "/src/images/icon/star.png",
        image2: "/src/images/icon/star.png",
        image3: "/src/images/icon/star.png",
        image4: "/src/images/icon/star.png",
        image5: "/src/images/icon/noStar.png",
      },
      offer: "",
      review: "145",
    },
    {
      name: "Kids Electric Car",
      price1: "$960",
      price2: "",
      image: "/src/images/products/14.png",
      rating: {
        image1: "/src/images/icon/star.png",
        image2: "/src/images/icon/star.png",
        image3: "/src/images/icon/star.png",
        image4: "/src/images/icon/star.png",
        image5: "/src/images/icon/star.png",
      },
      offer: "",
      review: "65",
    },
    {
      name: "Jr. Zoom Soccer Cleats",
      price1: "$1160",
      price2: "",
      image: "/src/images/products/15.png",
      rating: {
        image1: "/src/images/icon/star.png",
        image2: "/src/images/icon/star.png",
        image3: "/src/images/icon/star.png",
        image4: "/src/images/icon/star.png",
        image5: "/src/images/icon/star.png",
      },
      offer: "",
      review: "45",
    },
    {
      name: "GP11 Shooter USB Gamepad",
      price1: "$660",
      price2: "",
      image: "/src/images/products/16.png",
      rating: {
        image1: "/src/images/icon/star.png",
        image2: "/src/images/icon/star.png",
        image3: "/src/images/icon/star.png",
        image4: "/src/images/icon/star.png",
        image5: "/src/images/icon/star-half-filled.png",
      },
      offer: "",
      review: "96",
    },
    {
      name: "Quilted Satin Jacket",
      price1: "$660",
      price2: "",
      image: "/src/images/products/17.png",
      rating: {
        image1: "/src/images/icon/star.png",
        image2: "/src/images/icon/star.png",
        image3: "/src/images/icon/star.png",
        image4: "/src/images/icon/star.png",
        image5: "/src/images/icon/star-half-filled.png",
      },
      offer: "",
      review: "53",
    },
  ];
